Route4_Text_TrippedOverGeodude::
    .string "The entrance to MT. MOON\n"
    .string "is blocked.\p"
    .string "Lets hope they fix it\n"
    .string "in the next update.$"

Route4_Text_CrissyIntro::
    .string "I came to MT. MOON in search of\n"
    .string "rare POKéMON.$"

Route4_Text_CrissyDefeat::
    .string "I wanna catch more rare POKéMON!$"

Route4_Text_CrissyPostBattle::
    .string "There might not be any more\n"
    .string "rare POKéMON here.\p"
    .string "I think I got them all.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"

Route4_Text_RouteSign::
    .string "ROUTE 4\p"
    .string "WEST: MT. MOON\n"
    .string "EAST: CERULEAN CITY$"

Text_FirePunchTeach::
    .string "A blazing strike born of passion!\p"
    .string "Fueled by heat, driven by will!\p"
    .string "When courage burns brightest,\n"
    .string "FIRE PUNCH ignites the path to victory!\l"
    .string "You feel that flame within, yes?\p"
    .string "Then come!\n"
    .string "Let me teach it to your POKéMON!$"

Text_FirePunchDeclined::
    .string "You'll be back when you understand\n"
    .string "the worth of FIRE PUNCH.$"

Text_FirePunchWhichMon::
    .string "All right!\n"
    .string "Which POKéMON wants to learn it?$"

Text_FirePunchTaught::
    .string "Now, we are comrades.\n"
    .string "Go Team VALOR !!!\p"
    .string "You should go before you're seen\n"
    .string "by the misguided fools who train\l"
    .string "their thunder & ice moves.$"

Text_ThunderPunchTeach::
    .string "A strike charged with pure instinct!\p"
    .string "Electric power guided by trust!\p"
    .string "When your bond sparks true,\n"
    .string "THUNDER PUNCH lands with lightning precision!\l"
    .string "You feel that current between you, yes?\p"
    .string "Then let’s harness it!\n"
    .string "I’ll teach it to your POKéMON!$"

Text_ThunderPunchDeclined::
    .string "You'll be back when you understand\n"
    .string "the worth of THUNDER PUNCH.$"

Text_ThunderPunchWhichMon::
    .string "All right!\n"
    .string "Which POKéMON wants to learn it?$"

Text_ThunderPunchTaught::
    .string "Now, we are comrades.\n"
    .string "Go Team INSTINCT !!!\p"
    .string "You should go before you're seen\n"
    .string "by the misguided fools who train\l"
    .string "their fire & ice moves.$"

Text_IcePunchTeach::
    .string "A strike of serene, focused power.\p"
    .string "Cold as clarity, sharp as intellect.\p"
    .string "When emotion stills and mind leads,\n"
    .string "ICE PUNCH freezes doubt itself!\l"
    .string "You seek mastery over strength, yes?\p"
    .string "Then allow me.\n"
    .string "I shall teach it to your POKéMON!$"

Text_IcePunchDeclined::
    .string "You'll be back when you understand\n"
    .string "the worth of ICE PUNCH.$"

Text_IcePunchWhichMon::
    .string "All right!\n"
    .string "Which POKéMON wants to learn it?$"

Text_IcePunchTaught::
    .string "Now, we are comrades.\n"
    .string "Go Team MYSTIC!!!\p"
    .string "You should go before you're seen\n"
    .string "by the misguided fools who train\l"
    .string "their fire & thunder moves.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh, wow, that's the BOULDERBADGE!\n"
    .string "You got it from BROCK, didn't you?\p"
    .string "BROCK is cool. He's not just tough.\n"
    .string "People like and respect him.\p"
    .string "I want to become a GYM LEADER\n"
    .string "like him.$"
