@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "You can have this TM.\n"
    .string "I don't need it anymore…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "You can have this TM.\n"
    .string "I don't need it anymore…$"

Route12_NorthEntrance_2F_Text_ReceivedTM44FromLittleGirl::
    .string "{PLAYER} received TM44\n"
    .string "from the little girl.$"

Route12_NorthEntrance_2F_Text_ExplainTM44::
    .string "TM44 is a move called REST…\p"
    .string "It lets your POKéMON rest.\n"
    .string "Your pokemon will go to sleep\l"
    .string "and it will be fully healed.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "You don't have room for this.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's POKéMON TOWER!$"

